main: com.cavetale.hideandseek.HideAndSeekPlugin

name: HideAndSeek
version: 0.1
description: HideAndSeek Plugin
api-version: 1.19

author: StarTux
website: https://github.com/StarTux/HideAndSeek

depend: [Core, Title, Fam, Mytems]
softdepend: []

commands:

  hideandseek:
    aliases: [hsa]
    description: Hide And Seek User Command
    permission: hideandseek.hideandseek
    usage: /hsa

  hideandseekadmin:
    aliases: [hsaadm]
    description: HideAndSeek Admin Command
    permission: hideandseek.admin
    usage: /hsaadm

permissions:

  hideandseek.hideandseek:
    description: Use /hideandseek
    default: op

  hideandseek.admin:
    description: Use /hideandseekadmin
    default: op
